In [2]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
np?

In [2]:
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [4]:
array = np.array([1.25, 1, 4 ,2, 3])
array

array([1.25, 1.  , 4.  , 2.  , 3.  ])

In [5]:
array = np.array([1, 2, 3], dtype='float32')
array

array([1., 2., 3.], dtype=float32)

In [10]:
array2d = np.array([range(i, i+3)  for i in range(1, 4)])
array2d

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
np.zeros(10, dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [12]:
np.ones((3,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [14]:
np.full((3,4), 3.14, dtype='float16')

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]], dtype=float16)

In [15]:
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((3, 3))

array([[0.37168102, 0.56850153, 0.45562243],
       [0.52903769, 0.31576679, 0.66679952],
       [0.63958496, 0.94103495, 0.86540377]])

In [18]:
np.random.normal(0, 1, (3, 3))

array([[ 0.20004311, -0.1381566 , -1.22961883],
       [-0.60866796,  0.14434675,  0.03048633],
       [ 0.12987772, -0.77955913, -1.02221787]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.random.seed(0)

In [44]:
a = np.random.randint(0, 10, size = 5)
a

array([4, 2, 0, 3, 2])

In [45]:
b = np.random.randint(0, 10, size = (2, 3))
b

array([[0, 7, 5],
       [9, 0, 2]])

In [34]:
x = np.random.randint(0, 10, size = (2, 3, 3))
x

array([[[4, 4, 8],
        [4, 3, 7],
        [5, 5, 0]],

       [[1, 5, 9],
        [3, 0, 5],
        [0, 1, 2]]])

In [40]:
print("x ndim:  ", x.ndim)
print("x shape: ", x.shape)
print("x size:  ", x.size)

x ndim:   3
x shape:  (2, 3, 3)
x size:   18


In [42]:
print("dtype:    ", x.dtype)
print("itemsize: ", x.itemsize)
print("nbytes:   ", x.nbytes)

dtype:     int64
itemsize:  8
nbytes:    144


In [47]:
print("  0th:  ", a[0])
print("  3rd:  ", a[3])
print("  last: ", a[-1])
print("2nd last :", a[-2])

  0th:   4
  3rd:   3
  last:  2
2nd last : 3


In [48]:
b[0, 1] 

7

In [51]:
x[1, -1, 2]

2

In [53]:
x[1, -1, 2] = 5
x[1, -1, 2]

5

In [54]:
x[1, -1, 2] = 3.141592
x[1, -1, 2]

3

In [55]:
arr = np.arange(10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[5:]

array([5, 6, 7, 8, 9])

In [60]:
arr[4:7]

array([4, 5, 6])

In [61]:
arr[::2]

array([0, 2, 4, 6, 8])

In [63]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [64]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
arr[5::-2]

array([5, 3, 1])

In [70]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
x[:2, :3]

array([[0, 1, 2],
       [4, 5, 6]])

In [73]:
x[:3, ::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [74]:
x[::-1, ::-1]

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [75]:
x[:, 0]

array([ 0,  4,  8, 12])

In [78]:
print(x[1, :])

print(x[1])

[4 5 6 7]
[4 5 6 7]


In [83]:
x_ = x[1:3, 1:3]
x_

array([[ 5,  6],
       [ 9, 10]])

In [85]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
x_ *= 0

In [87]:
x_

array([[0, 0],
       [0, 0]])

In [88]:
x

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  7],
       [ 8,  0,  0, 11],
       [12, 13, 14, 15]])

---

In [97]:
x_ = x[:2, :2].copy()
x_

array([[0, 1],
       [4, 0]])

In [98]:
x

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  7],
       [ 8,  0,  0, 11],
       [12, 13, 14, 15]])

In [99]:
x_ += 10

In [100]:
x_

array([[10, 11],
       [14, 10]])

In [101]:
x

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  7],
       [ 8,  0,  0, 11],
       [12, 13, 14, 15]])

In [103]:
x.reshape(16)

array([ 0,  1,  2,  3,  4,  0,  0,  7,  8,  0,  0, 11, 12, 13, 14, 15])

In [104]:
x.reshape((2, 8))

array([[ 0,  1,  2,  3,  4,  0,  0,  7],
       [ 8,  0,  0, 11, 12, 13, 14, 15]])

In [122]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [123]:
a.reshape((1, 3))

array([[1, 2, 3]])

In [124]:
a.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [126]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [127]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [129]:
x = np.arange(8).reshape(2, 4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [136]:
y = np.arange(4).reshape(1, 4)
y

array([[0, 1, 2, 3]])

In [137]:
z = np.arange(4).reshape(2, 2)
z

array([[0, 1],
       [2, 3]])

In [142]:
print("x:\n", x)
print("\ny:\n", y)

np.concatenate([x, y])

x:
 [[0 1 2 3]
 [4 5 6 7]]

y:
 [[0 1 2 3]]


array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

In [145]:
np.vstack([x, y])

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

In [144]:
print("x:\n", x)
print("\nz:\n", z)

np.concatenate([x, z], axis = 1)

x:
 [[0 1 2 3]
 [4 5 6 7]]

z:
 [[0 1]
 [2 3]]


array([[0, 1, 2, 3, 0, 1],
       [4, 5, 6, 7, 2, 3]])

In [146]:
np.hstack([x, z])

array([[0, 1, 2, 3, 0, 1],
       [4, 5, 6, 7, 2, 3]])

In [153]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
a, b, c, d = np.split(arr, [4, 9, 13])

In [158]:
print("a: ", a)
print("b: ", b)
print("c: ", c)
print("d: ", d)

a:  [0 1 2 3]
b:  [4 5 6 7 8]
c:  [ 9 10 11 12]
d:  [13 14 15]


In [159]:
arr =arr.reshape((4, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [166]:
a, b = np.vsplit(arr, [2])

In [167]:
print("a:\n", a)
print("\nb:\n", b)

a:
 [[0 1 2 3]
 [4 5 6 7]]

b:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [170]:
c1, c2 = np.hsplit(a, [2])
c3, c4 = np.hsplit(b, [2])

In [171]:
print("c1:\n", c1)
print("\nc2:\n", c2)
print("\nc3:\n", c3)
print("\nc4:\n", c4)

c1:
 [[0 1]
 [4 5]]

c2:
 [[2 3]
 [6 7]]

c3:
 [[ 8  9]
 [12 13]]

c4:
 [[10 11]
 [14 15]]


In [172]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Universal Functions UFuncs
vectorized operations
two types unary and binary

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
x - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [7]:
x * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
x / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [9]:
x // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [10]:
-x

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [11]:
x % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

In [12]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
-(x - 1) ** 2

array([ -1,   0,  -1,  -4,  -9, -16, -25, -36, -49, -64])

actually wrappers for numpy functions <br> <br> works with python functions too

In [19]:
abs(-x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

__Trignometric functions__

In [35]:
np.pi

3.141592653589793

In [34]:
np.sin(30) 

-56.61004208597725

In [36]:
np.cos(90)

-0.4480736161291701

In [37]:
np.tan(45)

1.6197751905438615

In [42]:
np.arcsin(1)

1.5707963267948966

In [39]:
np.arccos(1)

0.0

In [41]:
np.arctan(1)

0.7853981633974483

__Exponents and logarithms__

In [62]:
x = [1, 2, 3]
x

[1, 2, 3]

In [63]:
np.exp(x) # e^x

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
np.exp2(x)  # 2^x

array([2., 4., 8.])

In [56]:
np.power(3, x)  # 3 ** x

array([ 3,  9, 27])

In [57]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [65]:
y = [2.71828, 2, 10]
y

[2.71828, 2, 10]

In [66]:
np.log(y)

array([0.99999933, 0.69314718, 2.30258509])

In [69]:
np.log2(y)

array([1.44269407, 1.        , 3.32192809])

In [70]:
np.log10(y)

array([0.43429419, 0.30103   , 1.        ])

use expm1 amd log1p for more precision while dealing with smaller inputs

### Advanced UFuncs
__<code><span style="color:green">from</span> scipy <span style="color:green">import</span> special__<br>
*gamma, beta, gaussian, error functions etc.*
    <hr>
    specifying where the output will be stored after an operation<br>
    _the following is skipped [compute -> store in temp -> assign]_

In [82]:
answer = np.zeros(10)
answer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
inter = np.power(np.arange(1,6), 2, out = answer[::2])
answer

array([ 1.,  0.,  4.,  0.,  9.,  0., 16.,  0., 25.,  0.])

In [85]:
np.add(np.arange(1,6), inter, out = answer[1::2])
answer

array([ 1.,  2.,  4.,  6.,  9., 12., 16., 20., 25., 30.])

__Aggregates__

In [125]:
x = np.random.randint(1, 100, 10)
x

array([23, 89, 94, 66, 14, 95, 47, 52, 46, 89])

In [126]:
np.add.reduce(x)

615

In [127]:
np.sum(x) # same as above

615

In [128]:
np.multiply.reduce(x)

169001404032901440

In [129]:
np.prod(x) # same as above

169001404032901440

store intermidate results

In [130]:
np.add.accumulate(x)

array([ 23, 112, 206, 272, 286, 381, 428, 480, 526, 615])

In [132]:
np.min(x)

14

In [146]:
np.argmin(x)

4

In [134]:
np.max(x)

95

In [147]:
np.argmax(x)

5

___
Statistics Aggregates
|

In [143]:
np.mean(x)

61.5

In [145]:
np.median(x)

59.0

In [144]:
np.var(x)

799.05

In [142]:
np.std(x)

28.267472472791052

**Multidimensional Aggregates**

In [136]:
m = np.random.randint(1, 100, (3,5))
m

array([[16, 46, 91, 39, 50],
       [ 9, 87, 99,  9, 23],
       [12,  1,  1, 22,  5]])

In [138]:
np.sum(m) #entire array

510

In [140]:
np.sum(m, axis=0) # collapse rows , dim of cols

array([ 37, 134, 191,  70,  78])

In [141]:
np.max(m, axis=1) # collapse cols , dim of rows

array([91, 99, 22])

the keyword <code>axis</code> in numpy aggregates specifies the dimension of the array that will be collapsed rather than array that will be aggregated and returned

most aggregate function are <code>NaN</code> safe, others need to be prefix with nan

#### NOTE : First step to summarize data with aggregates, 
*mean, standard deviation, median, min, max, sum, product, qunatiles etc.*

## Broadcasting
__It is simply set of rules for applying binary ufuncs on two arrays of different sizes__

In [149]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [150]:
a + 10

array([[10, 11, 12],
       [13, 14, 15]])

2d Array + Scalar (0d Array)
_streches or broadcasts to match the shape of higher dimensional array and fill with duplicate values which actually does not take place_
<br>**We can model above as follows**
```
[[0, 1, 2], + 10  => [[0, 1, 2], + [[10, 10, 10], = [[10, 11, 12],
 [3, 4, 5]]           [3, 4, 5]]    [10, 10, 10]]    [13, 14, 15]]
```

In [151]:
b = np.array([5, 10]).reshape((2,1))
b

array([[ 5],
       [10]])

In [152]:
a + b

array([[ 5,  6,  7],
       [13, 14, 15]])

**Visualisation of NumPy Broadcasting**
```
[[0, 1, 2], + [[ 5],  => [[0, 1, 2], + [[ 5,  5,  5], = [[ 5,  6,  7],
 [3, 4, 5]]    [10]]      [3, 4, 5]]    [10, 10, 10]]    [13, 14, 15]]
```

Here is a case when both arrays get broadcasted

In [153]:
a =  np.array([1, 2, 3]).reshape((1, 3))
a

array([[1, 2, 3]])

In [154]:
b =  np.array([4, 5, 6]).reshape((3, 1))
b

array([[4],
       [5],
       [6]])

In [155]:
a + b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

**Visualisation of NumPy Broadcasting**
```
               [[4],     [[1, 2, 3],     [[4, 4, 4],     [[5, 6, 7],
[[1, 2, 3]] +   [5],  =   [1, 2, 3],  +   [5, 5, 5],  =   [6, 7, 8],
                [6]]      [1, 2, 3]]      [6, 6, 6]]      [7, 8, 9]]
```
NOTE : Again, the extra memory is not actually allocated in the course of operation , but its useful conceptually to imagine such.