# Tensorflow - 
__Flow of tensors from operation to operation. A tensor is a multidimensional array (exactly like NumPy ndarray), but it can also store scalar (simple value like 10)__

In [1]:
import tensorflow as tf

Creating tensors with `tf.constant()`

In [5]:
t = tf.constant(100)
t

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [6]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
t.shape

TensorShape([2, 3])

In [8]:
t[:, :2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [13]:
t[:, 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [14]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [15]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
tf.